version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment: 
        TESTOPTS: "--ci-dir=$CIRCLE_TEST_REPORTS/test-results"

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: hello-world-{{ checksum "Gemfile.lock"}}

      # Bundle install dependencies
      - run: 
          name: install-dependencies
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: sinatra-demo-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle

      # Run minitest
      - run:
          name: test
          command: bundle exec rake

      # Save artifacts
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS/test-results

      # Create Docker build environment
      - setup_remote_docker:
          docker_layer_caching: true

      # Build image and push to Docker Hub
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ethnopunk/docker_repo:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ethnopunk/docker_repo


  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "54:66:66:c5:d9:0c:c5:4b:c6:b0:29:60:d1:a5:cb:9d"
      - run:
          name: stop running existing version of service
          command: |
            ssh ubuntu@34.254.188.32 "docker kill helloworld"
            ssh ubuntu@34.254.188.32 "docker rm helloworld"
      - run:
          name: pull and run new version of service
          command: |
            ssh ubuntu@34.254.188.32 "docker pull ethnopunk/docker_repo:$TAG"
            ssh ubuntu@34.254.188.32 "docker run -d -name helloworld -p 4567:4567 ethnopunk/docker_repo:$TAG"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build