version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment: 
        TESTOPTS: "--ci-dir=/tmp/test-results"
test:
  override:
    - bundle exec rake test:
        parallel: true
        files:
          - test/**/*.rb
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: hello-world-{{ checksum "Gemfile.lock"}}

      # Bundle install dependencies
      - run: 
          name: install-dependencies
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: sinatra-demo-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle

      # Run minitest
      - run:
          name: test
          command: bundle exec rake

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results